export const seedCourses = [
  { slug: 'chatgpt-crash-course', title: 'ChatGPT Crash Course', summary: 'Turn raw ideas into clear outputs with reliable prompts and structure.', duration_minutes: 16, level: 'Beginner', icon: '🤖' },
  { slug: 'midjourney-in-minutes', title: 'Midjourney in Minutes', summary: 'Fast image workflows, prompts and upscales without the fluff.', duration_minutes: 15, level: 'Beginner', icon: '🎨' },
  { slug: 'copilot-productive', title: 'GitHub Copilot for Productivity', summary: 'From completion to commits—ship faster with confidence.', duration_minutes: 17, level: 'Intermediate', icon: '💻' },
  { slug: 'notion-ai-research', title: 'Notion AI for Research', summary: 'Summarise, extract, and ideate in context.', duration_minutes: 14, level: 'Beginner', icon: '🗂️' },
  { slug: 'runway-gen2', title: 'Runway Gen-2 Quickstart', summary: 'Create short videos with AI—practical workflows that work.', duration_minutes: 13, level: 'Beginner', icon: '🎬' },
  { slug: 'perplexity-deep-dives', title: 'Perplexity for Deep Dives', summary: 'Verified research workflows and citations in minutes.', duration_minutes: 12, level: 'Beginner', icon: '🔎' },
  { slug: 'time-boxing-that-sticks', title: 'Time-Boxing That Sticks', summary: 'Plan days you can actually follow.', duration_minutes: 15, level: 'Beginner', icon: '📆' },
  { slug: 'second-brain-lite', title: 'Build a Second Brain Lite', summary: 'Lightweight capture, organise, and retrieve loop.', duration_minutes: 18, level: 'Beginner', icon: '🧠' },
  { slug: 'prompt-engineering-basics', title: 'Prompt Engineering Basics', summary: 'Roles, constraints, examples, evaluation.', duration_minutes: 17, level: 'Beginner', icon: '🧩' },
  { slug: 'meeting-os', title: 'Meeting Operating System', summary: 'Shorten meetings, clarify outcomes, document decisions.', duration_minutes: 14, level: 'Beginner', icon: '📝' },
  { slug: 'inbox-to-zero', title: 'Inbox to Zero in 15', summary: 'Filters, triage, and a weekly sweep.', duration_minutes: 15, level: 'Beginner', icon: '📨' },
  { slug: 'ai-daily-planner', title: 'AI Daily Planner', summary: 'Use AI to plan with realism and buffers.', duration_minutes: 13, level: 'Beginner', icon: '🗒️' },
  { slug: 'short-form-system', title: 'Short-Form Video System', summary: 'Idea → script → record → edit in a lunch break.', duration_minutes: 19, level: 'Intermediate', icon: '📱' },
  { slug: 'thumbnail-science', title: 'Thumbnail Science', summary: 'Patterns that get the click.', duration_minutes: 16, level: 'Beginner', icon: '🖼️' },
  { slug: 'script-templates-convert', title: 'Script Templates That Convert', summary: 'Never face a blank page again.', duration_minutes: 17, level: 'Beginner', icon: '📃' },
  { slug: 'audio-cleanup', title: 'Audio Cleanup in a Pinch', summary: 'Clearer sound with simple steps.', duration_minutes: 12, level: 'Beginner', icon: '🎧' },
  { slug: 'captioning-that-pops', title: 'Captioning That Pops', summary: 'Accessibility that also boosts retention.', duration_minutes: 13, level: 'Beginner', icon: '💬' },
  { slug: 'repurpose-like-a-pro', title: 'Repurpose Like a Pro', summary: 'Multiply outputs from one recording.', duration_minutes: 18, level: 'Intermediate', icon: '♻️' },
  { slug: 'zapier-minis', title: 'Zapier Mini-Automations', summary: 'Small wins that stack.', duration_minutes: 14, level: 'Beginner', icon: '⚡' },
  { slug: 'sheets-ai-formulas', title: 'Sheets + AI Formulas', summary: 'From data to answers fast.', duration_minutes: 16, level: 'Intermediate', icon: '📊' },
  { slug: 'canva-magic', title: 'Canva Magic Studio', summary: 'Design quicker with AI assistance.', duration_minutes: 15, level: 'Beginner', icon: '🖌️' },
  { slug: 'voice-cloning-primer', title: 'Voice Cloning Primer', summary: 'Ethics and quick demos.', duration_minutes: 12, level: 'Beginner', icon: '🎙️' },
  { slug: 'descript-edit-by-text', title: 'Descript: Edit by Text', summary: 'Cut ums and ahs with keystrokes.', duration_minutes: 17, level: 'Beginner', icon: '✂️' },
  { slug: 'data-to-slides', title: 'Data to Slides in Minutes', summary: 'Story from spreadsheet to deck.', duration_minutes: 13, level: 'Beginner', icon: '🪄' }
]
